
const Players=[
    {
      "name": "Messi",
      "photo": "https://cdn.sofifa.net/players/158/023/25_120.png",
      "position": "RW",
      "nationality": "https://cdn.sofifa.net/flags/ar.png",
      "club": "https://cdn.sofifa.net/meta/team/239235/120.png",
      "rating": 93,
      "shooting": 92,
      "passing": 91,
      "dribbling": 95,
      "defending": 35
    },
    {
      "name": "Ronaldo",
      "photo": "https://cdn.sofifa.net/players/020/801/25_120.png",
      "position": "ST",
      "nationality": "https://cdn.sofifa.net/flags/pt.png",
      "club": "https://cdn.sofifa.net/meta/team/2506/120.png",
      "rating": 93,
      "shooting": 92,
      "passing": 91,
      "dribbling": 95,
      "defending": 35
    },
    {
      "name": "Donnarumma",
      "photo": "https://cdn.sofifa.net/players/230/621/25_120.png",
      "position": "GK",
      "nationality": "https://cdn.sofifa.net/flags/it.png",
      "club": "https://cdn.sofifa.net/meta/team/591/120.png",
      "rating": 93,
      "diving": 92,
      "handling": 91,
      "kicking": 95,
      "reflexes": 35
    },{
      "name": "Bruyne",
      "photo": "https://cdn.sofifa.net/players/192/985/25_120.png",
      "position": "CM",
      "nationality": "https://cdn.sofifa.net/flags/be.png",
      "club": "https://cdn.sofifa.net/players/239/085/25_120.png",
      "rating": 93,
      "shooting": 92,
      "passing": 91,
      "dribbling": 95,
      "defending": 35
    },{
      "name": "Mbappé",
      "photo": "https://cdn.sofifa.net/players/231/747/25_120.png",
      "position": "ST",
      "nationality": "https://cdn.sofifa.net/flags/fr.png",
      "club": "https://cdn.sofifa.net/meta/team/3468/120.png",
      "rating": 93,
      "shooting": 92,
      "passing": 91,
      "dribbling": 95,
      "defending": 35
    },{
      "name": "van Dijk",
      "photo": "https://cdn.sofifa.net/players/203/376/25_120.png",
      "position": "CB",
      "nationality": "https://cdn.sofifa.net/flags/nl.png",
      "club": "https://cdn.sofifa.net/meta/team/8/120.png",
      "rating": 93,
      "shooting": 92,
      "passing": 91,
      "dribbling": 95,
      "defending": 35
    },{
      "name": "Rudiger",
      "photo": "https://cdn.sofifa.net/players/205/452/25_120.png",
      "position": "CB",
      "nationality": "https://cdn.sofifa.net/flags/de.png",
      "club": "https://cdn.sofifa.net/meta/team/3468/120.png",
      "rating": 93,
      "shooting": 92,
      "passing": 91,
      "dribbling": 95,
      "defending": 35
    },{
      "name": "Neymar",
      "photo": "https://cdn.sofifa.net/players/190/871/25_120.png",
      "position": "LW",
      "nationality": "https://cdn.sofifa.net/flags/br.png",
      "club": "https://cdn.sofifa.net/meta/team/7011/120.png",
      "rating": 93,
      "shooting": 92,
      "passing": 91,
      "dribbling": 95,
      "defending": 35
    },{
      "name": "Salah",
      "photo": "https://cdn.sofifa.net/players/191/059/25_120.png",
      "position": "RW",
      "nationality": "https://cdn.sofifa.net/flags/eg.png",
      "club": "https://cdn.sofifa.net/meta/team/8/120.png",
      "rating": 93,
      "shooting": 92,
      "passing": 91,
      "dribbling": 95,
      "defending": 35
    },{
      "name": "Kimmich",
      "photo": "https://cdn.sofifa.net/players/212/622/25_120.png",
      "position": "CM",
      "nationality": "https://cdn.sofifa.net/flags/de.png",
      "club": "https://cdn.sofifa.net/meta/team/503/120.png",
      "rating": 93,
      "shooting": 92,
      "passing": 91,
      "dribbling": 95,
      "defending": 35
    },
    {
      "name": "Jan Oblak",
      "photo": "https://cdn.sofifa.net/players/200/389/25_120.png",
      "position": "GK",
      "nationality": "https://cdn.sofifa.net/flags/si.png",
      "club": "https://cdn.sofifa.net/meta/team/7980/120.png",
      "rating": 93,
      "diving": 92,
      "handling": 91,
      "kicking": 95,
      "reflexes": 35
    },{
      "name": "Modrić",
      "photo": "https://cdn.sofifa.net/players/177/003/25_120.png",
      "position": "CM",
      "nationality": "https://cdn.sofifa.net/flags/hr.png",
      "club": "https://cdn.sofifa.net/meta/team/3468/120.png",
      "rating": 93,
      "shooting": 92,
      "passing": 91,
      "dribbling": 95,
      "defending": 35
    },{
      "name": "Vinicius",
      "photo": "https://cdn.sofifa.net/players/238/794/25_120.png",
      "position": "LW",
      "nationality": "https://cdn.sofifa.net/flags/br.png",
      "club": "https://cdn.sofifa.net/meta/team/3468/120.png",
      "rating": 93,
      "shooting": 92,
      "passing": 91,
      "dribbling": 95,
      "defending": 35
    },{
      "name": "Brahim",
      "photo": "https://cdn.sofifa.net/players/231/410/25_120.png",
      "position": "LW",
      "nationality": "https://cdn.sofifa.net/flags/ma.png",
      "club": "https://cdn.sofifa.net/meta/team/3468/120.png",
      "rating": 93,
      "shooting": 92,
      "passing": 91,
      "dribbling": 95,
      "defending": 35
    },{
      "name": "Benzema",
      "photo": "https://cdn.sofifa.net/players/165/153/25_120.png",
      "position": "ST",
      "nationality": "https://cdn.sofifa.net/flags/fr.png",
      "club": "https://cdn.sofifa.net/meta/team/476/120.png",
      "rating": 93,
      "shooting": 92,
      "passing": 91,
      "dribbling": 95,
      "defending": 35
    },{
      "name": "Haaland",
      "photo": "https://cdn.sofifa.net/players/239/085/25_120.png",
      "position": "ST",
      "nationality": "https://cdn.sofifa.net/flags/fr.png",
      "club": "https://cdn.sofifa.net/meta/team/476/120.png",
      "rating": 93,
      "shooting": 92,
      "passing": 91,
      "dribbling": 95,
      "defending": 35
    },{
      "name": "Kanté",
      "photo": "https://cdn.sofifa.net/players/215/914/25_120.png",
      "position": "CM",
      "nationality": "https://cdn.sofifa.net/flags/fr.png",
      "club": "https://cdn.sofifa.net/meta/team/476/120.png",
      "rating": 93,
      "shooting": 92,
      "passing": 91,
      "dribbling": 95,
      "defending": 35
    },{
      "name": "Davies",
      "photo": "https://cdn.sofifa.net/players/234/396/25_120.png",
      "position": "LB",
      "nationality": "https://cdn.sofifa.net/flags/ca.png",
      "club": "https://cdn.sofifa.net/meta/team/503/120.png",
      "rating": 93,
      "shooting": 92,
      "passing": 91,
      "dribbling": 95,
      "defending": 35
    },
    {
      "name": "Bounou",
      "photo": "https://cdn.sofifa.net/players/209/981/25_120.png",
      "position": "GK",
      "nationality": "https://cdn.sofifa.net/flags/ma.png",
      "club": "https://cdn.sofifa.net/meta/team/7011/120.png",
      "rating": 93,
      "diving": 92,
      "handling": 91,
      "kicking": 95,
      "reflexes": 35
    },{
      "name": "Fernandes",
      "photo": "https://cdn.sofifa.net/players/212/198/25_120.png",
      "position": "CM",
      "nationality": "https://cdn.sofifa.net/flags/pt.png",
      "club": "https://cdn.sofifa.net/meta/team/14/120.png",
      "rating": 93,
      "shooting": 92,
      "passing": 91,
      "dribbling": 95,
      "defending": 35
    },{
      "name": "Sancho",
      "photo": "https://cdn.sofifa.net/players/233/049/25_120.png",
      "position": "LW",
      "nationality": "https://cdn.sofifa.net/flags/gb-eng.png",
      "club": "https://cdn.sofifa.net/meta/team/14/120.png",
      "rating": 93,
      "shooting": 92,
      "passing": 91,
      "dribbling": 95,
      "defending": 35
    },{
      "name": "Arnold",
      "photo": "https://cdn.sofifa.net/players/231/281/25_120.png",
      "position": "RB",
      "nationality": "https://cdn.sofifa.net/flags/gb-eng.png",
      "club": "https://cdn.sofifa.net/meta/team/8/120.png",
      "rating": 93,
      "shooting": 92,
      "passing": 91,
      "dribbling": 95,
      "defending": 35
    },{
      "name": "Hakimi",
      "photo": "https://cdn.sofifa.net/players/235/212/25_120.png",
      "position": "RB",
      "nationality": "https://cdn.sofifa.net/flags/ma.png",
      "club": "https://cdn.sofifa.net/meta/team/591/120.png",
      "rating": 93,
      "shooting": 92,
      "passing": 91,
      "dribbling": 95,
      "defending": 35
    },{
      "name": "En-Nesyri",
      "photo": "https://cdn.sofifa.net/players/235/410/25_120.png",
      "position": "ST",
      "nationality": "https://cdn.sofifa.net/flags/ma.png",
      "club": "https://cdn.sofifa.net/meta/team/88/120.png",
      "rating": 93,
      "shooting": 92,
      "passing": 91,
      "dribbling": 95,
      "defending": 35
    },{
      "name": "Mazraoui",
      "photo": "https://cdn.sofifa.net/players/236/401/25_120.png",
      "position": "LB",
      "nationality": "https://cdn.sofifa.net/flags/ma.png",
      "club": "https://cdn.sofifa.net/meta/team/14/120.png",
      "rating": 93,
      "shooting": 92,
      "passing": 91,
      "dribbling": 95,
      "defending": 35
    }
  ];
  localStorage.setItem("Players",JSON.stringify(Players));